version: '3'

services:
  web:
    image: c0ny1/upload-labs:latest
    container_name: php_web
    volumes:
      - ./upload/:/var/www/html/upload/
      - ./docker-php.conf:/etc/apache2/conf-enabled/docker-php.conf
    ports:
      - "80:80"
